"""update participant table

Revision ID: 4cb0cb4bc2ac
Revises: 
Create Date: 2021-01-31 20:21:30.517420

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4cb0cb4bc2ac'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('participant',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=36), nullable=True),
    sa.Column('last_name', sa.String(length=84), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('lottery_code', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('participant')
    # ### end Alembic commands ###
